version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  game-logic:
    build: ./game-logic
    ports:
      - "3001:3001"
    networks:
      - app-network

  static-assets:
    build: ./static-assets
    ports:
      - "3002:80"
    networks:
      - app-network

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - game-logic
      - static-assets
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
